version: "3.6"

services:
  db:
    image: "mysql:8.0.26"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lechsys
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

networks: 
  default: 
    external: 
      name: external-example 