"""empty message

Revision ID: 0d5ec76b76d0
Revises: 990fff98978e
Create Date: 2021-11-08 12:36:35.007871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5ec76b76d0'
down_revision = '990fff98978e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('end', sa.Date(), nullable=True))
    op.drop_column('events', 'start_date')
    op.drop_column('events', 'end_date')
    op.add_column('users', sa.Column('state', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    op.add_column('events', sa.Column('end_date', sa.DATE(), nullable=True))
    op.add_column('events', sa.Column('start_date', sa.DATE(), nullable=True))
    op.drop_column('events', 'end')
    op.drop_column('events', 'start')
    # ### end Alembic commands ###
