"""empty message

Revision ID: 182584b061cf
Revises: 0e2206ce49c1
Create Date: 2021-11-01 12:03:55.174164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '182584b061cf'
down_revision = '0e2206ce49c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_basic_info', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_basic_info', 'positions', ['position_id'], ['id'])
    op.drop_column('user_basic_info', 'age')
    op.drop_column('user_basic_info', 'position')
    op.drop_column('user_basic_info', 'nationality')
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'nationalities', ['nationality'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'birth_date')
    op.add_column('user_basic_info', sa.Column('nationality', mysql.TEXT(), nullable=True))
    op.add_column('user_basic_info', sa.Column('position', mysql.TEXT(), nullable=True))
    op.add_column('user_basic_info', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_basic_info', type_='foreignkey')
    op.drop_column('user_basic_info', 'position_id')
    # ### end Alembic commands ###
