"""empty message

Revision ID: 1a3994946e95
Revises: bea4d6ad2c77
Create Date: 2021-11-01 11:53:22.317897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a3994946e95'
down_revision = 'bea4d6ad2c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='users_basic_info')
    op.drop_table('users_basic_info')
    op.create_foreign_key(None, 'user_basic_info', 'positions', ['position'], ['id'])
    op.drop_column('user_basic_info', 'age')
    op.drop_column('user_basic_info', 'nationality')
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'nationalities', ['nationality'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'birth_date')
    op.add_column('user_basic_info', sa.Column('nationality', mysql.TEXT(), nullable=True))
    op.add_column('user_basic_info', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_basic_info', type_='foreignkey')
    op.create_table('users_basic_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('height', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('weight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('position', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('nationality', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('shirt', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['nationality'], ['nationalities.id'], name='users_basic_info_ibfk_2'),
    sa.ForeignKeyConstraint(['position'], ['positions.id'], name='users_basic_info_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'users_basic_info', ['id'], unique=False)
    # ### end Alembic commands ###
