"""empty message

Revision ID: 1bb12dafc394
Revises: 0d5ec76b76d0
Create Date: 2021-11-08 12:41:37.242672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bb12dafc394'
down_revision = '0d5ec76b76d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'hour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('hour', mysql.TIME(), nullable=True))
    # ### end Alembic commands ###
