"""empty message

Revision ID: 2fc4ebf7f0b9
Revises: d3244c0cc1ed
Create Date: 2021-11-11 01:24:37.221174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fc4ebf7f0b9'
down_revision = 'd3244c0cc1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='motoric_resumes')
    op.drop_table('motoric_resumes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motoric_resumes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('field_time', mysql.TIME(), nullable=True),
    sa.Column('exertion_index', mysql.FLOAT(), nullable=True),
    sa.Column('exertion_index_per_minute', mysql.FLOAT(), nullable=True),
    sa.Column('total_player_load', mysql.FLOAT(), nullable=True),
    sa.Column('total_distance', mysql.FLOAT(), nullable=True),
    sa.Column('standing', mysql.FLOAT(), nullable=True),
    sa.Column('walking', mysql.FLOAT(), nullable=True),
    sa.Column('jogging', mysql.FLOAT(), nullable=True),
    sa.Column('running', mysql.FLOAT(), nullable=True),
    sa.Column('hsr', mysql.FLOAT(), nullable=True),
    sa.Column('sprint', mysql.FLOAT(), nullable=True),
    sa.Column('meterage_per_minute', mysql.FLOAT(), nullable=True),
    sa.Column('acceleration', mysql.FLOAT(), nullable=True),
    sa.Column('deceleration', mysql.FLOAT(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='motoric_resumes_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='motoric_resumes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'motoric_resumes', ['id'], unique=False)
    # ### end Alembic commands ###
