"""empty message

Revision ID: 43888557c92c
Revises: cfb8e4e6474e
Create Date: 2021-11-18 01:24:59.112141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43888557c92c'
down_revision = 'cfb8e4e6474e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpe', sa.Column('total_time', sa.Time(), nullable=True))
    op.add_column('wellness', sa.Column('total_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellness', 'total_time')
    op.drop_column('rpe', 'total_time')
    # ### end Alembic commands ###
