"""empty message

Revision ID: 5270944999c2
Revises: 2fc4ebf7f0b9
Create Date: 2021-11-12 22:28:36.317811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5270944999c2'
down_revision = '2fc4ebf7f0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motoric', sa.Column('date', sa.Date(), nullable=True))
    op.drop_index('id', table_name='motoric')
    op.create_index(op.f('ix_motoric_id'), 'motoric', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_motoric_id'), table_name='motoric')
    op.create_index('id', 'motoric', ['id'], unique=False)
    op.drop_column('motoric', 'date')
    # ### end Alembic commands ###
