"""empty message

Revision ID: 5802a1c96ece
Revises: 43888557c92c
Create Date: 2021-11-27 12:52:32.905044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5802a1c96ece'
down_revision = '43888557c92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contusion', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('kinase', sa.Column('state', sa.Text(), nullable=True))
    op.add_column('motoric', sa.Column('state', sa.Text(), nullable=True))
    op.add_column('rpe', sa.Column('state', sa.Text(), nullable=True))
    op.add_column('wellness', sa.Column('state', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellness', 'state')
    op.drop_column('rpe', 'state')
    op.drop_column('motoric', 'state')
    op.drop_column('kinase', 'state')
    op.drop_column('contusion', 'end')
    # ### end Alembic commands ###
