"""empty message

Revision ID: 7ae99f880eb7
Revises: 4f669a380223
Create Date: 2021-11-06 17:56:23.093499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae99f880eb7'
down_revision = '4f669a380223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_message_read_time')
    # ### end Alembic commands ###
