"""empty message

Revision ID: 7bfbe1d5c9b6
Revises: a3c1601727f7
Create Date: 2022-01-12 21:25:03.450721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfbe1d5c9b6'
down_revision = 'a3c1601727f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('name_pl', sa.String(length=128), nullable=True))
    op.add_column('notification', sa.Column('details_pl', sa.Text(), nullable=True))
    op.create_index(op.f('ix_notification_name_pl'), 'notification', ['name_pl'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_name_pl'), table_name='notification')
    op.drop_column('notification', 'details_pl')
    op.drop_column('notification', 'name_pl')
    # ### end Alembic commands ###
