"""empty message

Revision ID: 91138acdbb62
Revises: 
Create Date: 2021-09-02 19:41:55.026240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91138acdbb62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'latitude')
    # ### end Alembic commands ###
