"""empty message

Revision ID: 990fff98978e
Revises: 7ae99f880eb7
Create Date: 2021-11-07 23:51:04.630356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990fff98978e'
down_revision = '7ae99f880eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'state')
    # ### end Alembic commands ###
