"""empty message

Revision ID: cfb8e4e6474e
Revises: 5270944999c2
Create Date: 2021-11-14 18:15:43.851518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfb8e4e6474e'
down_revision = '5270944999c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellness', sa.Column('date', sa.Date(), nullable=True))
    op.drop_constraint('wellness_ibfk_2', 'wellness', type_='foreignkey')
    op.drop_column('wellness', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellness', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('wellness_ibfk_2', 'wellness', 'users', ['user_id'], ['id'])
    op.drop_column('wellness', 'date')
    # ### end Alembic commands ###
