"""empty message

Revision ID: d4b13f914e54
Revises: dd9f26a29d3f
Create Date: 2021-11-08 21:53:37.072897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4b13f914e54'
down_revision = 'dd9f26a29d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('notification', sa.Column('checked', sa.Boolean(), nullable=True))
    op.add_column('notification', sa.Column('link', sa.Text(), nullable=True))
    op.drop_column('notification', 'payload_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('payload_json', mysql.TEXT(), nullable=True))
    op.drop_column('notification', 'link')
    op.drop_column('notification', 'checked')
    op.drop_column('notification', 'details')
    # ### end Alembic commands ###
