"""empty message

Revision ID: dd9f26a29d3f
Revises: b75e01c8c99c
Create Date: 2021-11-08 14:39:11.414982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd9f26a29d3f'
down_revision = 'b75e01c8c99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'hour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('hour', mysql.TIME(), nullable=True))
    # ### end Alembic commands ###
