"""empty message

Revision ID: fa3f18bc8c98
Revises: 5802a1c96ece
Create Date: 2021-12-07 18:25:41.827387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3f18bc8c98'
down_revision = '5802a1c96ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('has_kinase', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'has_kinase')
    # ### end Alembic commands ###
