"""empty message

Revision ID: ff122dc2d373
Revises: 1a3994946e95
Create Date: 2021-11-01 11:57:44.344826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff122dc2d373'
down_revision = '1a3994946e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_basic_info', 'positions', ['position'], ['id'])
    op.drop_column('user_basic_info', 'age')
    op.drop_column('user_basic_info', 'nationality')
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'nationalities', ['nationality'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'birth_date')
    op.add_column('user_basic_info', sa.Column('nationality', mysql.TEXT(), nullable=True))
    op.add_column('user_basic_info', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_basic_info', type_='foreignkey')
    # ### end Alembic commands ###
