nationality_eng = {
    'AD': 'Andorra',
    'AE': 'United Arab Emirates',
    'AF': 'Afghanistan',
    'AG': 'Antigua & Barbuda',
    'AI': 'Anguilla',
    'AL': 'Albania',
    'AM': 'Armenia',
    'AN': 'Netherlands Antilles',
    'AO': 'Angola',
    'AQ': 'Antarctica',
    'AR': 'Argentina',
    'AS': 'American Samoa',
    'AT': 'Austria',
    'AU': 'Australia',
    'AW': 'Aruba',
    'AZ': 'Azerbaijan',
    'BA': 'Bosnia and Herzegovina',
    'BB': 'Barbados',
    'BD': 'Bangladesh',
    'BE': 'Belgium',
    'BF': 'Burkina Faso',
    'BG': 'Bulgaria',
    'BH': 'Bahrain',
    'BI': 'Burundi',
    'BJ': 'Benin',
    'BM': 'Bermuda',
    'BN': 'Brunei Darussalam',
    'BO': 'Bolivia',
    'BR': 'Brazil',
    'BS': 'Bahama',
    'BT': 'Bhutan',
    'BU': 'Burma (no longer exists)',
    'BV': 'Bouvet Island',
    'BW': 'Botswana',
    'BY': 'Belarus',
    'BZ': 'Belize',
    'CA': 'Canada',
    'CC': 'Cocos (Keeling) Islands',
    'CF': 'Central African Republic',
    'CG': 'Congo',
    'CH': 'Switzerland',
    'CI': 'Côte D\'ivoire (Ivory Coast)',
    'CK': 'Cook Iislands',
    'CL': 'Chile',
    'CM': 'Cameroon',
    'CN': 'China',
    'CO': 'Colombia',
    'CR': 'Costa Rica',
    'CS': 'Czechoslovakia (no longer exists)',
    'CU': 'Cuba',
    'CV': 'Cape Verde',
    'CX': 'Christmas Island',
    'CY': 'Cyprus',
    'CZ': 'Czech Republic',
    'DD': 'German Democratic Republic (no longer exists)',
    'DE': 'Germany',
    'DJ': 'Djibouti',
    'DK': 'Denmark',
    'DM': 'Dominica',
    'DO': 'Dominican Republic',
    'DZ': 'Algeria',
    'EC': 'Ecuador',
    'EE': 'Estonia',
    'EG': 'Egypt',
    'EH': 'Western Sahara',
    'ER': 'Eritrea',
    'ES': 'Spain',
    'ET': 'Ethiopia',
    'FI': 'Finland',
    'FJ': 'Fiji',
    'FK': 'Falkland Islands (Malvinas)',
    'FM': 'Micronesia',
    'FO': 'Faroe Islands',
    'FR': 'France',
    'FX': 'France, Metropolitan',
    'GA': 'Gabon',
    'GB': 'United Kingdom (Great Britain)',
    'GD': 'Grenada',
    'GE': 'Georgia',
    'GF': 'French Guiana',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GL': 'Greenland',
    'GM': 'Gambia',
    'GN': 'Guinea',
    'GP': 'Guadeloupe',
    'GQ': 'Equatorial Guinea',
    'GR': 'Greece',
    'GS': 'South Georgia and the South Sandwich Islands',
    'GT': 'Guatemala',
    'GU': 'Guam',
    'GW': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HK': 'Hong Kong',
    'HM': 'Heard & McDonald Islands',
    'HN': 'Honduras',
    'HR': 'Croatia',
    'HT': 'Haiti',
    'HU': 'Hungary',
    'ID': 'Indonesia',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IN': 'India',
    'IO': 'British Indian Ocean Territory',
    'IQ': 'Iraq',
    'IR': 'Islamic Republic of Iran',
    'IS': 'Iceland',
    'IT': 'Italy',
    'JM': 'Jamaica',
    'JO': 'Jordan',
    'JP': 'Japan',
    'KE': 'Kenya',
    'KG': 'Kyrgyzstan',
    'KH': 'Cambodia',
    'KI': 'Kiribati',
    'KM': 'Comoros',
    'KN': 'St. Kitts and Nevis',
    'KP': 'Korea, Democratic People\'s Republic of',
    'KR': 'Korea, Republic of',
    'KW': 'Kuwait',
    'KY': 'Cayman Islands',
    'KZ': 'Kazakhstan',
    'LA': 'Lao People\'s Democratic Republic',
    'LB': 'Lebanon',
    'LC': 'Saint Lucia',
    'LI': 'Liechtenstein',
    'LK': 'Sri Lanka',
    'LR': 'Liberia',
    'LS': 'Lesotho',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'LV': 'Latvia',
    'LY': 'Libyan Arab Jamahiriya',
    'MA': 'Morocco',
    'MC': 'Monaco',
    'MD': 'Moldova, Republic of',
    'MG': 'Madagascar',
    'MH': 'Marshall Islands',
    'ML': 'Mali',
    'MN': 'Mongolia',
    'MM': 'Myanmar',
    'MO': 'Macau',
    'MP': 'Northern Mariana Islands',
    'MQ': 'Martinique',
    'MR': 'Mauritania',
    'MS': 'Monserrat',
    'MT': 'Malta',
    'MU': 'Mauritius',
    'MV': 'Maldives',
    'MW': 'Malawi',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'MZ': 'Mozambique',
    'NA': 'Namibia',
    'NC': 'New Caledonia',
    'NE': 'Niger',
    'NF': 'Norfolk Island',
    'NG': 'Nigeria',
    'NI': 'Nicaragua',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'NP': 'Nepal',
    'NR': 'Nauru',
    'NT': 'Neutral Zone (no longer exists)',
    'NU': 'Niue',
    'NZ': 'New Zealand',
    'OM': 'Oman',
    'PA': 'Panama',
    'PE': 'Peru',
    'PF': 'French Polynesia',
    'PG': 'Papua New Guinea',
    'PH': 'Philippines',
    'PK': 'Pakistan',
    'PL': 'Poland',
    'PM': 'St. Pierre & Miquelon',
    'PN': 'Pitcairn',
    'PR': 'Puerto Rico',
    'PT': 'Portugal',
    'PW': 'Palau',
    'PY': 'Paraguay',
    'QA': 'Qatar',
    'RE': 'Réunion',
    'RO': 'Romania',
    'RU': 'Russian Federation',
    'RW': 'Rwanda',
    'SA': 'Saudi Arabia',
    'SB': 'Solomon Islands',
    'SC': 'Seychelles',
    'SD': 'Sudan',
    'SE': 'Sweden',
    'SG': 'Singapore',
    'SH': 'St. Helena',
    'SI': 'Slovenia',
    'SJ': 'Svalbard & Jan Mayen Islands',
    'SK': 'Slovakia',
    'SL': 'Sierra Leone',
    'SM': 'San Marino',
    'SN': 'Senegal',
    'SO': 'Somalia',
    'SR': 'Suriname',
    'ST': 'Sao Tome & Principe',
    'SU': 'Union of Soviet Socialist Republics (no longer exists)',
    'SV': 'El Salvador',
    'SY': 'Syrian Arab Republic',
    'SZ': 'Swaziland',
    'TC': 'Turks & Caicos Islands',
    'TD': 'Chad',
    'TF': 'French Southern Territories',
    'TG': 'Togo',
    'TH': 'Thailand',
    'TJ': 'Tajikistan',
    'TK': 'Tokelau',
    'TM': 'Turkmenistan',
    'TN': 'Tunisia',
    'TO': 'Tonga',
    'TP': 'East Timor',
    'TR': 'Turkey',
    'TT': 'Trinidad & Tobago',
    'TV': 'Tuvalu',
    'TW': 'Taiwan, Province of China',
    'TZ': 'Tanzania, United Republic of',
    'UA': 'Ukraine',
    'UG': 'Uganda',
    'UM': 'United States Minor Outlying Islands',
    'US': 'United States of America',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VA': 'Vatican City State (Holy See)',
    'VC': 'St. Vincent & the Grenadines',
    'VE': 'Venezuela',
    'VG': 'British Virgin Islands',
    'VI': 'United States Virgin Islands',
    'VN': 'Viet Nam',
    'VU': 'Vanuatu',
    'WF': 'Wallis & Futuna Islands',
    'WS': 'Samoa',
    'YD': 'Democratic Yemen (no longer exists)',
    'YE': 'Yemen',
    'YT': 'Mayotte',
    'YU': 'Yugoslavia',
    'ZA': 'South Africa',
    'ZM': 'Zambia',
    'ZR': 'Zaire',
    'ZW': 'Zimbabwe',
    'ZZ': 'Unknown or unspecified country',
}

var = ['Andorra', 'United Arab Emirates', 'Afghanistan', 'Antigua & Barbuda', 'Anguilla', 'Albania', 'Armenia',
       'Netherlands Antilles', 'Angola', 'Antarctica', 'Argentina', 'American Samoa', 'Austria', 'Australia', 'Aruba',
       'Azerbaijan', 'Bosnia and Herzegovina', 'Barbados', 'Bangladesh', 'Belgium', 'Burkina Faso', 'Bulgaria',
       'Bahrain', 'Burundi', 'Benin', 'Bermuda', 'Brunei Darussalam', 'Bolivia', 'Brazil', 'Bahama', 'Bhutan',
       'Burma (no longer exists)', 'Bouvet Island', 'Botswana', 'Belarus', 'Belize', 'Canada',
       'Cocos (Keeling) Islands', 'Central African Republic', 'Congo', 'Switzerland', "Côte D'ivoire (Ivory Coast)",
       'Cook Iislands', 'Chile', 'Cameroon', 'China', 'Colombia', 'Costa Rica', 'Czechoslovakia (no longer exists)',
       'Cuba', 'Cape Verde', 'Christmas Island', 'Cyprus', 'Czech Republic',
       'German Democratic Republic (no longer exists)', 'Germany', 'Djibouti', 'Denmark', 'Dominica',
       'Dominican Republic', 'Algeria', 'Ecuador', 'Estonia', 'Egypt', 'Western Sahara', 'Eritrea', 'Spain', 'Ethiopia',
       'Finland', 'Fiji', 'Falkland Islands (Malvinas)', 'Micronesia', 'Faroe Islands', 'France',
       'France, Metropolitan', 'Gabon', 'United Kingdom (Great Britain)', 'Grenada', 'Georgia', 'French Guiana',
       'Ghana', 'Gibraltar', 'Greenland', 'Gambia', 'Guinea', 'Guadeloupe', 'Equatorial Guinea', 'Greece',
       'South Georgia and the South Sandwich Islands', 'Guatemala', 'Guam', 'Guinea-Bissau', 'Guyana', 'Hong Kong',
       'Heard & McDonald Islands', 'Honduras', 'Croatia', 'Haiti', 'Hungary', 'Indonesia', 'Ireland', 'Israel', 'India',
       'British Indian Ocean Territory', 'Iraq', 'Islamic Republic of Iran', 'Iceland', 'Italy', 'Jamaica', 'Jordan',
       'Japan', 'Kenya', 'Kyrgyzstan', 'Cambodia', 'Kiribati', 'Comoros', 'St. Kitts and Nevis',
       "Korea, Democratic People's Republic of", 'Korea, Republic of', 'Kuwait', 'Cayman Islands', 'Kazakhstan',
       "Lao People's Democratic Republic", 'Lebanon', 'Saint Lucia', 'Liechtenstein', 'Sri Lanka', 'Liberia', 'Lesotho',
       'Lithuania', 'Luxembourg', 'Latvia', 'Libyan Arab Jamahiriya', 'Morocco', 'Monaco', 'Moldova, Republic of',
       'Madagascar', 'Marshall Islands', 'Mali', 'Mongolia', 'Myanmar', 'Macau', 'Northern Mariana Islands',
       'Martinique', 'Mauritania', 'Monserrat', 'Malta', 'Mauritius', 'Maldives', 'Malawi', 'Mexico', 'Malaysia',
       'Mozambique', 'Namibia', 'New Caledonia', 'Niger', 'Norfolk Island', 'Nigeria', 'Nicaragua', 'Netherlands',
       'Norway', 'Nepal', 'Nauru', 'Neutral Zone (no longer exists)', 'Niue', 'New Zealand', 'Oman', 'Panama', 'Peru',
       'French Polynesia', 'Papua New Guinea', 'Philippines', 'Pakistan', 'Poland', 'St. Pierre & Miquelon', 'Pitcairn',
       'Puerto Rico', 'Portugal', 'Palau', 'Paraguay', 'Qatar', 'Réunion', 'Romania', 'Russian Federation', 'Rwanda',
       'Saudi Arabia', 'Solomon Islands', 'Seychelles', 'Sudan', 'Sweden', 'Singapore', 'St. Helena', 'Slovenia',
       'Svalbard & Jan Mayen Islands', 'Slovakia', 'Sierra Leone', 'San Marino', 'Senegal', 'Somalia', 'Suriname',
       'Sao Tome & Principe', 'Union of Soviet Socialist Republics (no longer exists)', 'El Salvador',
       'Syrian Arab Republic', 'Swaziland', 'Turks & Caicos Islands', 'Chad', 'French Southern Territories', 'Togo',
       'Thailand', 'Tajikistan', 'Tokelau', 'Turkmenistan', 'Tunisia', 'Tonga', 'East Timor', 'Turkey',
       'Trinidad & Tobago', 'Tuvalu', 'Taiwan, Province of China', 'Tanzania, United Republic of', 'Ukraine', 'Uganda',
       'United States Minor Outlying Islands', 'United States of America', 'Uruguay', 'Uzbekistan',
       'Vatican City State (Holy See)', 'St. Vincent & the Grenadines', 'Venezuela', 'British Virgin Islands',
       'United States Virgin Islands', 'Viet Nam', 'Vanuatu', 'Wallis & Futuna Islands', 'Samoa',
       'Democratic Yemen (no longer exists)', 'Yemen', 'Mayotte', 'Yugoslavia', 'South Africa', 'Zambia', 'Zaire',
       'Zimbabwe', 'Unknown or unspecified country']



panstwa = [('Andorra', 'Andora'), ('United Arab Emirates', 'Zjednoczone Emiraty Arabskie'), ('Afghanistan', 'Afganistan'), ('Antigua & Barbuda', 'Antigua i Barbuda'), ('Anguilla', 'Anguilla'), ('Albania', 'Albania'), ('Armenia', 'Armenia'), ('Netherlands Antilles', 'Antyle Holenderskie'), ('Angola', 'Angola'), ('Antarctica', 'Antarktyda'), ('Argentina', 'Argentyna'), ('American Samoa', 'Samoa Amerykańskie'), ('Austria', 'Austria'), ('Australia', 'Australia'), ('Aruba', 'Aruba'), ('Azerbaijan', 'Azerbejdżan'), ('Bosnia and Herzegovina', 'Bośnia i Hercegowina'), ('Barbados', 'Barbados'), ('Bangladesh', 'Bangladesz'), ('Belgium', 'Belgia'), ('Burkina Faso', 'Burkina Faso'), ('Bulgaria', 'Bułgaria'), ('Bahrain', 'Bahrajn'), ('Burundi', 'Burundi'), ('Benin', 'Benin'), ('Bermuda', 'Bermudy'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Bolivia', 'Boliwia'), ('Brazil', 'Brazylia'), ('Bahama', 'Bahama'), ('Bhutan', 'Bhutan'), ('Burma (no longer exists)', 'Birma (już nie istnieje)'), ('Bouvet Island', 'Wyspa Bouveta'), ('Botswana', 'Botswana'), ('Belarus', 'Białoruś'), ('Belize', 'Belize'), ('Canada', 'Kanada'), ('Cocos (Keeling) Islands', 'Wyspy Kokosowe (Keelinga)'), ('Central African Republic', 'Republika Środkowoafrykańska'), ('Congo', 'Kongo'), ('Switzerland', 'Szwajcaria'), ("Côte D'ivoire (Ivory Coast)", 'Wybrzeże Kości Słoniowej (Ivory Coast)'), ('Cook Iislands', 'Wyspy Cooka'), ('Chile', 'Chile'), ('Cameroon', 'Kamerun'), ('China', 'Chiny'), ('Colombia', 'Kolumbia'), ('Costa Rica', 'Kostaryka'), ('Czechoslovakia (no longer exists)', 'Czechosłowacja (już nie istnieje)'), ('Cuba', 'Kuba'), ('Cape Verde', 'Wyspy Zielonego Przylądka'), ('Christmas Island', 'Wyspa Bożego Narodzenia'), ('Cyprus', 'Cypr'), ('Czech Republic', 'Republika Czeska'), ('German Democratic Republic (no longer exists)', 'Niemiecka Republika Demokratyczna (już nie istnieje)'), ('Germany', 'Niemcy'), ('Djibouti', 'Dżibuti'), ('Denmark', 'Dania'), ('Dominica', 'Dominika'), ('Dominican Republic', 'Republika Dominikańska'), ('Algeria', 'Algieria'), ('Ecuador', 'Ekwador'), ('Estonia', 'Estonia'), ('Egypt', 'Egipt'), ('Western Sahara', 'Sahara Zachodnia'), ('Eritrea', 'Erytrea'), ('Spain', 'Hiszpania'), ('Ethiopia', 'Etiopia'), ('Finland', 'Finlandia'), ('Fiji', 'Fidżi'), ('Falkland Islands (Malvinas)', 'Falklandy (Malwiny)'), ('Micronesia', 'Mikronezja'), ('Faroe Islands', 'Wyspy Owcze'), ('France', 'Francja'), ('France, Metropolitan', 'Francja, metropolia'), ('Gabon', 'Gabon'), ('United Kingdom (Great Britain)', 'Zjednoczone Królestwo (Wielka Brytania)'), ('Grenada', 'Grenada'), ('Georgia', 'Gruzja'), ('French Guiana', 'Gujana Francuska'), ('Ghana', 'Ghana'), ('Gibraltar', 'Gibraltar'), ('Greenland', 'Grenlandia'), ('Gambia', 'Gambia'), ('Guinea', 'Gwinea'), ('Guadeloupe', 'Gwadelupa'), ('Equatorial Guinea', 'Gwinea Równikowa'), ('Greece', 'Grecja'), ('South Georgia and the South Sandwich Islands', 'Południowa Georgia i Południowe Wyspy Sandwich'), ('Guatemala', 'Gwatemala'), ('Guam', 'Guam'), ('Guinea-Bissau', 'Gwinea Bissau'), ('Guyana', 'Gujana'), ('Hong Kong', 'Hongkong'), ('Heard & McDonald Islands', 'Wyspy Heard i McDonald'), ('Honduras', 'Honduras'), ('Croatia', 'Chorwacja'), ('Haiti', 'Haiti'), ('Hungary', 'Węgry'), ('Indonesia', 'Indonezja'), ('Ireland', 'Irlandia'), ('Israel', 'Izrael'), ('India', 'Indie'), ('British Indian Ocean Territory', 'Brytyjskie Terytorium Oceanu Indyjskiego'), ('Iraq', 'Irak'), ('Islamic Republic of Iran', 'Islamska Republika Iranu'), ('Iceland', 'Islandia'), ('Italy', 'Włochy'), ('Jamaica', 'Jamajka'), ('Jordan', 'Jordania'), ('Japan', 'Japonia'), ('Kenya', 'Kenia'), ('Kyrgyzstan', 'Kirgistan'), ('Cambodia', 'Kambodża'), ('Kiribati', 'Kiribati'), ('Comoros', 'Komory'), ('St. Kitts and Nevis', 'St. Kitts i Nevis'), ("Korea, Democratic People's Republic of", 'Koreańska Republika Ludowo-Demokratyczna'), ('Korea, Republic of', 'Korea, Republika Korei'), ('Kuwait', 'Kuwejt'), ('Cayman Islands', 'Kajmany'), ('Kazakhstan', 'Kazachstan'), ("Lao People's Democratic Republic", 'Laotańska Republika Ludowo-Demokratyczna'), ('Lebanon', 'Liban'), ('Saint Lucia', 'Saint Lucia'), ('Liechtenstein', 'Liechtenstein'), ('Sri Lanka', 'Sri Lanka'), ('Liberia', 'Liberia'), ('Lesotho', 'Lesotho'), ('Lithuania', 'Litwa'), ('Luxembourg', 'Luksemburg'), ('Latvia', 'Łotwa'), ('Libyan Arab Jamahiriya', 'Libijska Arabska Dżamahirija'), ('Morocco', 'Maroko'), ('Monaco', 'Monako'), ('Moldova, Republic of', 'Mołdawia, Republika Mołdowy'), ('Madagascar', 'Madagaskaru'), ('Marshall Islands', 'Wyspy Marshalla'), ('Mali', 'Mali'), ('Mongolia', 'Mongolia'), ('Myanmar', 'Myanmar'), ('Macau', 'Makau'), ('Northern Mariana Islands', 'Mariany Północne'), ('Martinique', 'Martynika'), ('Mauritania', 'Mauretania'), ('Monserrat', 'Monserrat'), ('Malta', 'Malta'), ('Mauritius', 'Mauritius'), ('Maldives', 'Malediwy'), ('Malawi', 'Malawi'), ('Mexico', 'Meksyk'), ('Malaysia', 'Malezja'), ('Mozambique', 'Mozambik'), ('Namibia', 'Namibia'), ('New Caledonia', 'Nowa Kaledonia'), ('Niger', 'Niger'), ('Norfolk Island', 'Wyspa Norfolk'), ('Nigeria', 'Nigeria'), ('Nicaragua', 'Nikaragua'), ('Netherlands', 'Niderlandy'), ('Norway', 'Norwegia'), ('Nepal', 'Nepal'), ('Nauru', 'Nauru'), ('Neutral Zone (no longer exists)', 'Strefa Neutralna (już nie istnieje)'), ('Niue', 'Niue'), ('New Zealand', 'Nowa Zelandia'), ('Oman', 'Oman'), ('Panama', 'Panama'), ('Peru', 'Peru'), ('French Polynesia', 'Polinezja Francuska'), ('Papua New Guinea', 'Papua-Nowa Gwinea'), ('Philippines', 'Filipiny'), ('Pakistan', 'Pakistan'), ('Poland', 'Polska'), ('St. Pierre & Miquelon', 'St. Pierre i Miquelon'), ('Pitcairn', 'Pitcairn'), ('Puerto Rico', 'Puerto Rico'), ('Portugal', 'Portugalia'), ('Palau', 'Palau'), ('Paraguay', 'Paragwaj'), ('Qatar', 'Katar'), ('Réunion', 'Reunion'), ('Romania', 'Rumunia'), ('Russian Federation', 'Federacja Rosyjska'), ('Rwanda', 'Rwanda'), ('Saudi Arabia', 'Arabia Saudyjska'), ('Solomon Islands', 'Wyspy Salomona'), ('Seychelles', 'Seszele'), ('Sudan', 'Sudan'), ('Sweden', 'Szwecja'), ('Singapore', 'Singapur'), ('St. Helena', 'Święta Helena'), ('Slovenia', 'Słowenia'), ('Svalbard & Jan Mayen Islands', 'Svalbard i Wyspy Jan Mayen'), ('Slovakia', 'Słowacja'), ('Sierra Leone', 'Sierra Leone'), ('San Marino', 'San Marino'), ('Senegal', 'Senegal'), ('Somalia', 'Somalia'), ('Suriname', 'Surinam'), ('Sao Tome & Principe', 'Wyspy Świętego Tomasza i Książęca (Sao Tome & Principe)'), ('Union of Soviet Socialist Republics (no longer exists)', 'Związek Socjalistycznych Republik Radzieckich (już nie istnieje)'), ('El Salvador', 'Salwador'), ('Syrian Arab Republic', 'Syryjska Republika Arabska'), ('Swaziland', 'Suazi'), ('Turks & Caicos Islands', 'Wyspy Turks i Caicos'), ('Chad', 'Czad'), ('French Southern Territories', 'Francuskie Terytoria Południowe'), ('Togo', 'Togo'), ('Thailand', 'Tajlandia'), ('Tajikistan', 'Tadżykistan'), ('Tokelau', 'Tokelau'), ('Turkmenistan', 'Turkmenistan'), ('Tunisia', 'Tunezja'), ('Tonga', 'Tonga'), ('East Timor', 'Timor Wschodni'), ('Turkey', 'Turcja'), ('Trinidad & Tobago', 'Trynidad i Tobago'), ('Tuvalu', 'Tuvalu'), ('Taiwan, Province of China', 'Tajwan, Prowincja Chin'), ('Tanzania, United Republic of', 'Tanzania, Zjednoczona Republika'), ('Ukraine', 'Ukraina'), ('Uganda', 'Uganda'), ('United States Minor Outlying Islands', 'Mniejsze Wyspy Przybrzeżne Stanów Zjednoczonych'), ('United States of America', 'Stany Zjednoczone Ameryki'), ('Uruguay', 'Urugwaj'), ('Uzbekistan', 'Uzbekistan'), ('Vatican City State (Holy See)', 'Państwo Watykańskie (Stolica Apostolska)'), ('St. Vincent & the Grenadines', 'St. Vincent i Grenadyny'), ('Venezuela', 'Wenezuela'), ('British Virgin Islands', 'Brytyjskie Wyspy Dziewicze'), ('United States Virgin Islands', 'Wyspy Dziewicze Stanów Zjednoczonych'), ('Viet Nam', 'Wietnam'), ('Vanuatu', 'Vanuatu'), ('Wallis & Futuna Islands', 'Wyspy Wallis i Futuna'), ('Samoa', 'Samoa'), ('Democratic Yemen (no longer exists)', 'Demokratyczny Jemen (już nie istnieje)'), ('Yemen', 'Jemen'), ('Mayotte', 'Majotta'), ('Yugoslavia', 'Jugosławia'), ('South Africa', 'Republika Południowej Afryki'), ('Zambia', 'Zambia'), ('Zaire', 'Zair'), ('Zimbabwe', 'Zimbabwe'), ('Unknown or unspecified country', 'Kraj nieznany lub nieokreślony')]